### ISSUE TITLE
feature request: a way to "restart" the OpenVR connection inside OBS

### ISSUE THREAD

**Issue by ragesaq** [baffler/OBS-OpenVR-Input-Plugin#29] opened 2020-05-02 21:58 UTC
I've had a few incidents on the latest OBS OpenVR Input plugin where OBS ceases to work, and the causes seem to range from switching between VR games and having to restart SteamVR. 
I've tried turning off displaying the input plugin and switching scenes with no luck, my only fix is to restart OBS which is not very convenient if you are in the middle of a broadcast.

**Comment by baffler** [comment] 2020-05-06 06:22
What exactly is happening, like a black screen for the OpenVR capture source? I would need a way to recreate the issue, something that I could reproduce on my end. Does it happen every time you switch VR games for example?

**Comment by ragesaq** [comment] 2020-05-08 07:37
That is correct, openvr capture sources are blank even if I change scene collections to another collection that doesn't have openVR.
As far as recreating it, the most consistent way that seems to do it is to restart steam with OBS actively using the openVR capture. When Steam comes back a lot of times it is black and only a restart of OBS will resolve this.

**Comment by owlmostdead** [comment] 2020-05-24 14:10
A feature where the OpenVR Plugin re-hooks into SteamVR would be fantastic. As said the issue is that when SteamVR crashed or closed, the OpenVR Plugin will not be able to detect SteamVR, only a restart of OBS helps. This is the only reason I stopped using the Plugin.

**Comment by baffler** [comment] 2020-08-05 03:16
I can't seem to ever recreate this issue, tried closing SteamVR many times with OBS running and it always seems to detect it every time. But I added a button in the properties anyways to reinitialize just in case. It will be in the next update which should be out soon.

**Comment by baffler** [comment] 2020-08-24 18:55
Got this added in [v1.5](https://github.com/baffler/OBS-OpenVR-Input-Plugin/releases/tag/v1.5)

**Closed** 2020-08-29 08:02 UTC
